version: '3.8'

services:
  myapp:
    image: myapp:1
    ports:
      - "8080:5000"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16.2
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
